apiVersion: v2
appVersion: "v1.10.4" # image "vectorim/element-web"
description: Communicate the way you want with Riot - a universal secure chat app entirely under your control.
icon: https://raw.githubusercontent.com/vector-im/element-web/develop/res/themes/element/img/logos/element-logo.svg
name: element-web
version: 1.0.34
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
  - element
home: https://element.io/
sources:
  - https://github.com/vector-im/element-web
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Bump upstream version to 1.10.3
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: element-web
      image: "vectorim/element-web:v1.10.4"
